### Name: Aryan Kumar
### Class: CSJ (G1)
### SystemID: 2023416075

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.0.2


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
m = np.empty(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
np.size(m)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(array)
print(non_zero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.78255905 0.82980016 0.48447331]
  [0.25282053 0.86401527 0.14363177]
  [0.58310058 0.78936461 0.18303284]]

 [[0.87189756 0.44704868 0.4069707 ]
  [0.78032448 0.4398612  0.21822773]
  [0.39235209 0.10318039 0.80390422]]

 [[0.06532344 0.79568492 0.21401115]
  [0.51250254 0.23114799 0.18097512]
  [0.29017032 0.24194979 0.31131366]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:\n", random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
 [[0.7364447  0.77332612 0.22765435 0.02987376 0.32220428 0.63840455
  0.0522851  0.08058669 0.1800608  0.8456483 ]
 [0.53518861 0.85272313 0.27765165 0.71395096 0.10091697 0.93367502
  0.35714968 0.27315267 0.91393442 0.92412357]
 [0.33791524 0.41895858 0.82839215 0.35970034 0.88791235 0.3644734
  0.56593855 0.60565652 0.57391464 0.01283062]
 [0.29128237 0.24154171 0.21835884 0.8454726  0.66384233 0.94943555
  0.63206637 0.77660069 0.20763017 0.62571077]
 [0.62922773 0.24833497 0.53566261 0.84327823 0.31504535 0.77664995
  0.92315791 0.2664663  0.80020499 0.7073535 ]
 [0.01156588 0.14340397 0.5548841  0.76512192 0.10349961 0.61834132
  0.24122948 0.677613   0.52345697 0.20705646]
 [0.31998114 0.33908919 0.89972123 0.81886114 0.19473702 0.7294968
  0.06814871 0.77002278 0.11683909 0.40682797]
 [0.73337182 0.15661797 0.18010361 0.1767117  0.87278856 0.67242028
  0.72644199 0.73965548 0.87098857 0.82221881]
 [0.6500808  0.37665863 0.78627595 0.20516658 0.01050451 0.7737772


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
matrix = np.zeros((5, 5))

matrix[1, 0] = 1
matrix[2, 1] = 2
matrix[3, 2] = 3
matrix[4, 3] = 4

print("5x5 Matrix with values just below the diagonal:\n", matrix)

5x5 Matrix with values just below the diagonal:
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
original_array = np.array([[1, 2], [3, 4]])
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
results = {
    "0 * np.nan": 0 * np.nan,
    "np.nan == np.nan": np.nan == np.nan,
    "np.inf > np.nan": np.inf > np.nan,
    "np.nan - np.nan": np.nan - np.nan,
    "np.nan in set([np.nan])": np.nan in set([np.nan]),
    "0.3 == 3 * 0.1": 0.3 == 3 * 0.1
}

for expression, result in results.items():
    print(f"{expression}: {result}")

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print("5x5 Matrix with values just below the diagonal:\n", matrix)

5x5 Matrix with values just below the diagonal:
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
# Create an 8x8 checkerboard pattern using ★ and ☆
size = 8
for row in range(size):
    line = ''
    for col in range(size):
        if (row + col) % 2 == 0:
            line += '★ '
        else:
            line += '☆ '
    print(line.strip())


★ ☆ ★ ☆ ★ ☆ ★ ☆
☆ ★ ☆ ★ ☆ ★ ☆ ★
★ ☆ ★ ☆ ★ ☆ ★ ☆
☆ ★ ☆ ★ ☆ ★ ☆ ★
★ ☆ ★ ☆ ★ ☆ ★ ☆
☆ ★ ☆ ★ ☆ ★ ☆ ★
★ ☆ ★ ☆ ★ ☆ ★ ☆
☆ ★ ☆ ★ ☆ ★ ☆ ★


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
import numpy as np

shape = (6, 7, 8)
index = 99

xyz = np.unravel_index(index, shape)
print(xyz)


(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
import numpy as np

# Define the basic 2x2 pattern
pattern = np.array([[1, 0],
                    [0, 1]])

# Tile it to create an 8x8 matrix
checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
# prompt: normalize  Normalize a 5x5 random matrix (★☆☆)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
Z


array([[ 1.04787369, -1.23703696, -0.75385516, -0.40117056, -1.1975998 ],
       [ 0.15908032, -0.43555702,  1.65027314, -1.391528  ,  1.33957471],
       [-0.48722015,  1.2162307 ,  1.75926886,  0.17276134,  0.24426562],
       [ 0.09173127,  0.82671366,  0.59576427, -1.27760183, -0.28116245],
       [ 1.25768983,  0.49160783, -1.43359497, -0.76955765, -1.18695071]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
# prompt:  Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
# prompt: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result_matrix = np.dot(matrix1, matrix2)
result_matrix


array([[0.04662116, 0.12309197],
       [0.43271804, 0.9483347 ],
       [0.79681415, 1.29787902],
       [1.50484728, 1.67884254],
       [0.91407376, 1.02299424]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
# prompt:  Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

import numpy as np

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z


array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
sum([0, 1, 2, 3, 4], -1) # = 0 + 1 + 2 + 3 + 4 + (-1) = 9
# Note: the above is a comment and not executable code.
# The following shows the correct way to calculate the sum.

# correct way:
sum([0, 1, 2, 3, 4, -1])

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
# prompt: Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z
# onsider an integer vector Z, which of these expressions are legal? (★☆☆)

Z = np.arange(10)

print(Z**Z) # Legal
print(2 << Z >> 2) # Legal
print(Z <- Z) # Legal
print(1j*Z) # Legal
print(Z/1/1) # Legal
#print(Z<Z>Z) # Illegal


[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
# prompt: What are the result of the following expressions? (★☆☆)
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


<ipython-input-31-4af80301be92>:8: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-31-4af80301be92>:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-31-4af80301be92>:10: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)