In [1]:
list1=[1,2,3]
list2=[4,5,6]
print(list1 +list2)

[1, 2, 3, 4, 5, 6]


In [2]:
print("subtraction:",list1-list2)
print("multiplication:",list1*list2)
print("division:",list1//list2)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [3]:
import numpy as np

list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Convert lists to NumPy arrays for element-wise operations
array1 = np.array(list1)
array2 = np.array(list2)

print("subtraction:", array1 - array2)
print("multiplication:", array1 * array2)
print("division:", array1 // array2)

subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0 0 0]


In [4]:


matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.identity(3)

result = np.dot(matrix_a, matrix_b)

print("Matrix A (1 to 9):")
print(matrix_a)

print("\nMatrix B (Identity Matrix):")
print(matrix_b)

print("\nResult of multiplication:")
print(result)


Matrix A (1 to 9):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B (Identity Matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Result of multiplication:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:
matrix_a=np.array[[1,2,3]
                  [2,3,1]
                  [1,1,2]]
matrix_b= np.array([1]

solution=np.linalg.solve(matrix_a,matrix_b)
x,y,z=solution
print(x,y,z)





<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-6-f19011a3bc48>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  matrix_a=np.array[[1,2,3]


TypeError: list indices must be integers or slices, not tuple

In [7]:
import numpy as np

# Coefficients matrix
A = np.array([[1, 2, 3],
              [2, 3, 1],
              [1, 1, 2]])

# Constants matrix
B = np.array([10, 15, 20])

# Solve the system of equations
solution = np.linalg.solve(A, B)

x, y, z = solution

print(f"x = {x}, y = {y}, z = {z}")


x = 26.25, y = -13.75, z = 3.75


In [8]:
A.T

array([[1, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [9]:
A.T

array([[1, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [11]:
np.min(A)


np.int64(1)

In [12]:
np.max(A)

np.int64(3)

In [13]:
np.sum(A)

np.int64(16)

In [14]:
rand_mat2=np.random.rand(5,5)
rand_mat2

array([[0.56276438, 0.68222225, 0.59735584, 0.6044926 , 0.00593371],
       [0.83995616, 0.17207523, 0.84853949, 0.86486451, 0.14486312],
       [0.4856644 , 0.18522788, 0.03177261, 0.28807658, 0.55870454],
       [0.19663432, 0.66880669, 0.39172868, 0.04690186, 0.53252865],
       [0.84129749, 0.62764215, 0.92107712, 0.35059402, 0.48333548]])

In [15]:
print(np.mean(rand_mat2))
print(np.std(rand_mat2))
print(np.var(rand_mat2))

0.4773223913721734
0.2779055842326751
0.07723151374770447


In [16]:
rand_mat3=np.random.randint(2,6,10)
rand_mat3

array([2, 5, 3, 5, 4, 5, 3, 3, 2, 2])

In [17]:
rand_arr=np.random.randint(0,100,10)
rand_arr>0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
rand_arr(rand_arr>0)

In [25]:
rand_arr1 = np.random.randint(0, 5, size=(5, 5))
print(rand_arr1)

i = 2
j = 2
for i in range(rand_arr1.shape[0]): # Iterate over rows
  for j in range(rand_arr1.shape[1]): # Iterate over columns
    print(rand_arr1[i][j])  # Access elements using i and j as indices
    if (i == 4 and j == 4):
      break  # Exit the loops if i and j reach 4

[[4 1 4 4 4]
 [2 2 1 0 4]
 [2 3 2 1 3]
 [4 3 1 0 3]
 [3 0 2 1 2]]
4
1
4
4
4
2
2
1
0
4
2
3
2
1
3
4
3
1
0
3
3
0
2
1
2
